/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1diseñodesistemas;

import static java.lang.String.valueOf;

/**
 *
 * @author Ronald
 */

//agregar metodo que cree paneles dinamicos segun la cantidad de sectores

//agregar funcionalidades a ambos botones

//crear ventana donde se puedan poner los datos del animal que agregamos

public class VentanaZoo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaZoo
     */
    public VentanaZoo() {
        initComponents();
        zoo.agregarEmpleado(juan);
        zoo.agregarEmpleado(gonchi);
        zoo.agregarEmpleado(flor);
        zoo.agregarSector(sector1);
        zoo.agregarSector(sector2);
        zoo.agregarSector(sector3);
        
        sector3.agregarAnimal(leon1);
        sector3.agregarAnimal(leon2);
        sector2.agregarAnimal(elefante1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        botonAgregarAnimal = new javax.swing.JButton();
        botonCalcularComida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalComidaCarnivoros = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalComidaHerbivoros = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalComida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonAgregarAnimal.setText("Agregar Animal");

        botonCalcularComida.setText("Calcular Comida");
        botonCalcularComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularComidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Kgs Carnivoros");

        totalComidaCarnivoros.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Kgs Herbivoros");

        totalComidaHerbivoros.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kgs Total");

        totalComida.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAgregarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCalcularComida))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(totalComidaCarnivoros)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalComidaHerbivoros)
                    .addComponent(totalComida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(botonAgregarAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCalcularComida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalComidaCarnivoros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalComidaHerbivoros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalComida)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(445, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularComidaActionPerformed
        // TODO add your handling code here:
        float comidaTotal;
        float comidaHer;
        float comidaCar;
        
        comidaCar = zoo.calcularComida(Alimentacion.CARNIVORO);
        comidaHer = zoo.calcularComida(Alimentacion.HERBIVORO);
        comidaTotal = comidaCar + comidaHer;
        
        totalComidaHerbivoros.setText(Float.toString(comidaHer));
        totalComidaCarnivoros.setText(Float.toString(comidaCar));
        totalComida.setText(Float.toString(comidaTotal));
    }//GEN-LAST:event_botonCalcularComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaZoo().setVisible(true);
            }
        });
    }
    
        Pais arg = new Pais("Argentina", "ARG");
        Pais bra = new Pais("Brasil","BRA");
        Pais uru = new Pais("Uruguay", "URU");
        Pais chi = new Pais("Chile", "CHI");
        Especie leon = new Especie("León", 30, Alimentacion.CARNIVORO);
        Especie lobo = new Especie("Lobo", 20, Alimentacion.CARNIVORO);
        Especie jirafa = new Especie("Jirafa", 0, Alimentacion.HERBIVORO);
        Especie elefante = new Especie("Elefante",0,Alimentacion.HERBIVORO);
        Zoologico zoo = new Zoologico();
        Empleado juan = new Empleado("Juan", "Balcarce 500", 40900987);
        Empleado gonchi = new Empleado("Gonzalo", "Juan B Teran 690", 47892000);
        Empleado flor = new Empleado("Florencia Noelia", "Rio Sali 777", 44032111);
        Sector sector1 = new Sector(1, 80.5437, 66.5766, Alimentacion.CARNIVORO);
        Sector sector2 = new Sector(2, 11.5437, 64.5766, Alimentacion.HERBIVORO);
        Sector sector3 = new Sector(3, 90.5437, 65.5766, Alimentacion.CARNIVORO);
        Carnivoro leon1 = new Carnivoro(15, 90000, chi, sector3, leon);
        Carnivoro leon2 = new Carnivoro(5, 400, arg, sector3, leon);
        
        Herbivoro elefante1 = new Herbivoro(60, 800, 15, chi, sector2, elefante);
        
        
           
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarAnimal;
    private javax.swing.JButton botonCalcularComida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel totalComida;
    private javax.swing.JLabel totalComidaCarnivoros;
    private javax.swing.JLabel totalComidaHerbivoros;
    // End of variables declaration//GEN-END:variables
}
